USE [insta]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FullSizeProfileVisit](
	[UserID] [varchar](50) NOT NULL,
	[TargetUserID] [varchar](50) NOT NULL,
	[VisitTime] [datetime] NOT NULL
 CONSTRAINT [PK_FullSizeProfileVisit] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[TargetUserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO