USE [insta]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UserTrends](
	[UserID] [varchar](50) NOT NULL,
	[Time] [datetime] NOT NULL,
	[Media] [int] NOT NULL,
	[Follows] [int] NOT NULL,
	[Followers] [int] NOT NULL
 CONSTRAINT [PK_UserTrends] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[Time] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO