USE [insta]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MediaFans](
	[MediaID] [varchar](50) NOT NULL,
	[UserID] [varchar](50) NOT NULL,
	[Liked] [bit] NOT NULL,
	[Commented] [bit] NOT NULL
 CONSTRAINT [PK_MediaFans] PRIMARY KEY CLUSTERED 
(
	[MediaID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO