USE [insta]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[IPGLogs](
	[ID] [bigint] IDENTITY(1, 1) NOT NULL,
	[Action] [varchar](50) NOT NULL,
	[UserID] [varchar](50) NULL,
	[DeviceID] [varchar](50) NULL,
	[DeviceModel] [varchar](50) NULL,
	[TargetUserID] [varchar](50) NULL,
	[Time] [datetime] NOT NULL
 CONSTRAINT [PK_IPGLogs] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO