USE [insta]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AppPurchase](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UserID] [varchar](50) NULL,
	[AppName] [varchar](50) NOT NULL,
	[PurchaseID] [varchar](30) NOT NULL,
	[Amount] [int] NOT NULL,
	[PaymentProvider] [varchar](30) NOT NULL,
	[AgentID] [varchar](50) NULL,
	[Time] [datetime] NOT NULL
 CONSTRAINT [PK_AppPurchase] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO